runtime: nodejs20
instance_class: F1
service: default

handlers:
  - url: /static
    static_dir: build/static
  - url: /index.html
    static_files: build/index.html
    upload: build/index.html
  - url: /
    static_files: build/index.html
    upload: build/index.html
